public enum StatType
{
    Health,
    MaxHealth,
    Mana,
    MaxMana,
    Speed,
    DodgeChance,
    ArmourRating,
    Strength,
    Dexterity,
    Intelligence,
    Endurance,
    FireResistance,
    IceResistance,
    PoisonResistance,
    RadiationResistance,
    PiercingResistance,
    BluntResistance,
    HitChance,
    MiscastChance
}
